name: cpp11-exercises

on: [push]

jobs:
    build:         
        runs-on: ubuntu-latest
        environment: build
        container:
            image: feabhas/ubuntu-projects:latest
            options: -u 1001
        steps:
            - name: checkout
              uses: actions/checkout@v4
              with:
                sparse-checkout: exercises
                fetch-depth: 1
            - name: build datalogger template
              run: |
                cp -r /home/feabhas/projects/cmake-host .
                cp -r exercises/templates/datalogger/* cmake-host
                cd cmake-host
                bash ./build.sh                   
            - name: build solutions
              run: |
                cp -r /home/feabhas/projects/cmake-host .
                cd cmake-host
                bash ./build-one.sh --all    
